-- Deploy gimmespace:2020-12-01-ViolationType_auto_inc to mysql

BEGIN;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE ViolationType DROP PRIMARY KEY, MODIFY violationTypeId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY;
SET FOREIGN_KEY_CHECKS=1;

COMMIT;
