-- Deploy gimmespace:2020-11-29_incidentId_auto_inc to mysql

BEGIN;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE Incident DROP PRIMARY KEY, MODIFY incidentId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY;
SET FOREIGN_KEY_CHECKS=1;

COMMIT;
