-- Deploy gimmespace:2020-12-01-Location_auto_inc to mysql

BEGIN;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE Location DROP PRIMARY KEY, MODIFY locationId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY;
SET FOREIGN_KEY_CHECKS=1;

COMMIT;
